--liquibase formatted sql
--changeset vavramchuk:1
CREATE TABLE app_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    birthday DATE
);
INSERT INTO app_user (name, surname, birthday) VALUES
    ('John', 'Doe', '1990-01-01'),
    ('Alice', 'Smith', '1985-03-15'),
    ('Bob', 'Johnson', '1992-07-20'),
    ('Eva', 'Miller', '1988-09-10'),
    ('Chris', 'Brown', '1995-12-05'),
    ('Emma', 'Wilson', '1983-04-25'),
    ('Frank', 'Williams', '1998-06-30'),
    ('Grace', 'Jones', '1980-11-18'),
    ('Henry', 'Davis', '1993-02-08'),
    ('Isabel', 'Clark', '1987-08-12');
