--liquibase formatted sql
--changeset vavramchuk:1

CREATE TABLE subscription (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    user_id INTEGER REFERENCES app_user(id),
    start_date DATE
);

INSERT INTO subscription (user_id, start_date) VALUES
    (1, '2022-01-15'),
    (2, '2022-02-20'),
    (3, '2022-03-25'),
    (4, '2022-04-10'),
    (5, '2022-05-12'),
    (6, '2022-06-18'),
    (7, '2022-07-30'),
    (8, '2022-08-05'),
    (9, '2022-09-15'),
    (10, '2022-10-22');
